src/Domain/Entity/Metric.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Domain\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Orchestra\Domain\Metric\MetricEnum;
use Orchestra\Domain\Repository\MetricDoctrineRepository;
use Orchestra\Infrastructure\Doctrine\Traits\TimestampedEntityTrait;

#[ORM\Entity(repositoryClass: MetricDoctrineRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Metric
{
    use TimestampedEntityTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $product = null;

    #[ORM\OneToMany(mappedBy: 'metric', targetEntity: Datapoint::class, cascade: [
        'persist',
        'remove',
    ], orphanRemoval: true)]
    private Collection $datapoints;

    #[ORM\ManyToOne(inversedBy: 'metrics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Endpoint $endpoint = null;

    #[ORM\Column(type: 'MetricEnumType', length: 255)]
    private ?MetricEnum $discriminator = null;

    public function __construct()
    {
        $this->datapoints = new ArrayCollection();
    }

    public function addDatapoint(Datapoint $datapoint): self
    {
        if (!$this->datapoints->contains($datapoint)) {
            $this->datapoints->add($datapoint);
            $datapoint->setMetric($this);
        }

        return $this;
    }

    public function belongsToEndpoint(Endpoint $endpoint): bool
    {
        if (!$this->endpoint instanceof Endpoint) {
            return false;
        }

        return $this->endpoint->getId() === $endpoint->getId();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Datapoint>
     */
    public function getDatapoints(): Collection
    {
        return $this->datapoints;
    }

    public function getDiscriminator(): ?MetricEnum
    {
        return $this->discriminator;
    }

    public function setDiscriminator(MetricEnum $discriminator): self
    {
        $this->discriminator = $discriminator;

        return $this;
    }

    public function getEndpoint(): ?Endpoint
    {
        return $this->endpoint;
    }

    public function setEndpoint(?Endpoint $endpoint): self
    {
        $this->endpoint = $endpoint;

        return $this;
    }

    public function getLastDatapoint(): ?Datapoint
    {
        $datapoint = $this->datapoints->last();

        return $datapoint instanceof Datapoint ? $datapoint : null;
    }

    public function getProduct(): ?string
    {
        return $this->product;
    }

    public function setProduct(string $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function removeDatapoint(Datapoint $datapoint): self
    {
        if ($this->datapoints->removeElement($datapoint)) {
            // set the owning side to null (unless already changed)
            if ($datapoint->getMetric() === $this) {
                $datapoint->setMetric(null);
            }
        }

        return $this;
    }
}

src/Web/Form/EndpointForm.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Web\Form;

use Orchestra\Domain\Endpoint\Driver\DriverEnum;
use Orchestra\Domain\Entity\Application;
use Orchestra\Domain\Entity\Endpoint;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EndpointForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('application', EntityType::class, [
                'class'        => Application::class,
                'choice_label' => static fn(Application $u) => $u->getName(),
                'disabled'     => true,
            ])
            ->add('url', UrlType::class, [
                'label' => 'URL to fetch',
            ])
            ->add('driver', EnumType::class, [
                'class'        => DriverEnum::class,
                'choice_label' => static fn(DriverEnum $d) => $d->getFriendlyName(),
            ])
            ->add('driverOptions', TextareaType::class, [
                'mapped' => false,
            ])
            ->add('submit', SubmitType::class, [
                'row_attr' => [
                    'class' => 'mb-0', // remove the mb-3 class
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Endpoint::class,
        ]);
    }
}

src/Web/Controller/EndpointController.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Web\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use JsonException;
use Orchestra\Domain\Collection\MetricsPerProductCollection;
use Orchestra\Domain\Endpoint\EndpointClient;
use Orchestra\Domain\Endpoint\EndpointDriverResponseMapper;
use Orchestra\Domain\Entity\Application;
use Orchestra\Domain\Entity\Endpoint;
use Orchestra\Domain\Entity\Metric;
use Orchestra\Domain\Entity\User;
use Orchestra\Domain\Exception\EndpointDriverNotInstantiableException;
use Orchestra\Domain\Exception\EndpointExecutionFailedException;
use Orchestra\Domain\Exception\InvalidMetricValueException;
use Orchestra\Domain\Repository\EndpointRepositoryInterface;
use Orchestra\Infrastructure\Controller\AppContext;
use Orchestra\Web\Breadcrumb\Breadcrumb;
use Orchestra\Web\Breadcrumb\BreadcrumbBuilder;
use Orchestra\Web\Exception\BreadcrumbBuilderException;
use Orchestra\Web\Exception\BreadcrumbException;
use Orchestra\Web\Form\EndpointForm;
use Orchestra\Web\Helper\BreadcrumbHelper;
use Orchestra\Web\Helper\Flash;
use Orchestra\Web\ViewModel\MetricViewModel;
use Psr\Log\LoggerInterface;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[AppContext('app_management')]
#[Breadcrumb('Applications', 'web_application_index')]
class EndpointController extends AbstractController
{
    public function __construct(
        private readonly EndpointRepositoryInterface $endpointRepository,
        private readonly BreadcrumbBuilder $breadcrumbBuilder,
        private readonly LoggerInterface $logger
    ) {
    }

    /**
     * @throws BreadcrumbException
     * @throws BreadcrumbBuilderException
     */
    #[Route(
        '/applications/{applicationId}/endpoints/create',
        name: 'web_endpoint_create',
        methods: ["GET", "POST"]
    )]
    public function createAction(
        #[MapEntity(id: 'applicationId')] Application $application,
        Request $request
    ): Response {
        BreadcrumbHelper::request($request)->add([
            'application' => $this->breadcrumbBuilder->application($application),
            'current'     => $this->breadcrumbBuilder->text('Create endpoint', true),
        ]);

        $endpoint = new Endpoint();
        $endpoint->setApplication($application);

        $form = $this->createForm(EndpointForm::class, $endpoint);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $driverOptions = json_decode(
                    (string)$form->get('driverOptions')->getData(),
                    true,
                    512,
                    JSON_THROW_ON_ERROR
                );

                if (!is_array($driverOptions)) {
                    $driverOptions = [$driverOptions];
                }
                $endpoint->setDriverOptions($driverOptions);
                $endpoint->setInterval(30);

                $this->endpointRepository->save($endpoint);
                $this->addFlash(Flash::OK, 'The endpoint has been created.');

                return $this->redirectToRoute(
                    'web_endpoint_details',
                    ['applicationId' => $application->getId(), 'id' => $endpoint->getId()]
                );
            } catch (JsonException) {
                // no-op, re-enter the form
                $form->addError(
                    new FormError(
                        'The driver options must be valid JSON'
                    )
                );
            }
        }

        return $this->render('endpoints/create.html.twig', [
            'application' => $application,
            'endpoint'    => $endpoint,
            'form'        => $form,
        ]);
    }

    #[Route(
        '/endpoint/{id}/delete',
        name: 'web_endpoint_delete',
        methods: ["POST"]
    )]
    public function deleteAction(Endpoint $endpoint): Response
    {
        $this->endpointRepository->delete($endpoint);

        $this->addFlash(Flash::OK, 'The endpoint has been deleted.');

        return $this->redirectToRoute('web_application_details', ['id' => $endpoint->getApplication()?->getId()]);
    }

    /**
     * @throws BreadcrumbException
     * @throws BreadcrumbBuilderException
     */
    #[Route(
        '/applications/{applicationId}/endpoints/{id}',
        name: 'web_endpoint_details',
        methods: ["GET"]
    )]
    public function detailsAction(
        #[MapEntity(id: 'applicationId')] Application $application,
        Endpoint $endpoint,
        Request $request
    ): Response {
        if (!$endpoint->belongsToApplication($application)) {
            throw $this->createNotFoundException();
        }

        BreadcrumbHelper::request($request)->add([
            'application' => $this->breadcrumbBuilder->application($application),
            'endpoint'    => $this->breadcrumbBuilder->endpoint($endpoint, true),
        ]);

        $metricsPerProduct = MetricsPerProductCollection::fromMetricCollection($endpoint->getMetrics());

        $user = $this->getUser();

        /** @var ArrayCollection<string, ArrayCollection<MetricViewModel>> $lastMetricsPerProduct */
        $lastMetricsPerProduct = $metricsPerProduct->map(
            static fn(ArrayCollection $metrics) => $metrics->map(
                fn(Metric $m) => MetricViewModel::fromLastDatapointInMetric($m)
                                                ->setPinned(
                                                    $user instanceof User
                                                        ? $user->decoratePinnedMetrics()->hasPinnedMetric($m)
                                                        : false
                                                )
            )
        );

        return $this->render('endpoints/details.html.twig', [
            'application'           => $application,
            'endpoint'              => $endpoint,
            'lastMetricsPerProduct' => $lastMetricsPerProduct,
        ]);
    }

    #[Route(
        '/applications/{applicationId}/endpoints/{id}/test',
        name: 'web_endpoint_test',
        methods: ["GET"]
    )]
    public function testAction(
        #[MapEntity(id: 'applicationId')] Application $application,
        Endpoint $endpoint,
        EndpointClient $endpointClient,
        EndpointDriverResponseMapper $mapper
    ): Response {
        try {
            $response = $endpointClient->fetch($endpoint);

            $log = $mapper->createCollectionLog($endpoint, $response);
            $endpoint->addCollectionLog($log);

            $endpoint = $mapper->map($endpoint, $response);
            $endpoint->touchLastSuccessfulResponse();

            $this->endpointRepository->save($endpoint);

            $this->addFlash(Flash::OK, 'The endpoint has been tested.');
        } catch (EndpointExecutionFailedException $e) {
            $this->addFlash(Flash::ERROR, 'The endpoint failed to execute; is it reachable?');

            $this->logger->warning(
                sprintf(
                    'Endpoint execution failed for endpoint %d: %s',
                    $endpoint->getId(),
                    $e->getMessage()
                )
            );
        } catch (EndpointDriverNotInstantiableException $e) {
            $this->addFlash(Flash::ERROR, 'The endpoint driver could not be instantiated. This is an internal error.');

            $this->logger->warning(
                sprintf(
                    'Endpoint driver could not be instantiated: %s',
                    $e->getMessage()
                )
            );
        } catch (InvalidMetricValueException $e) {
            $this->addFlash(Flash::ERROR, 'One or more metric values could not be encoded.');

            $this->logger->warning(
                sprintf(
                    'Invalid metric value: %s',
                    $e->getMessage()
                )
            );
        }

        return $this->redirectToRoute(
            'web_endpoint_details',
            ['applicationId' => $application->getId(), 'id' => $endpoint->getId()]
        );
    }

    /**
     * @throws BreadcrumbException
     * @throws BreadcrumbBuilderException
     */
    #[Route(
        '/applications/{applicationId}/endpoints/{id}/update',
        name: 'web_endpoint_update',
        methods: ["GET", "POST"]
    )]
    public function updateAction(
        #[MapEntity(id: 'applicationId')] Application $application,
        Endpoint $endpoint,
        Request $request
    ): Response {
        if (!$endpoint->belongsToApplication($application)) {
            throw $this->createNotFoundException();
        }

        BreadcrumbHelper::request($request)->add([
            'application' => $this->breadcrumbBuilder->application($application),
            'endpoint'    => $this->breadcrumbBuilder->endpoint($endpoint),
            'current'     => $this->breadcrumbBuilder->text('Update endpoint', true),
        ]);

        $form = $this->createForm(EndpointForm::class, $endpoint);
        try {
            $form->get('driverOptions')->setData(json_encode($endpoint->getDriverOptions(), JSON_THROW_ON_ERROR));
        } catch (JsonException $e) {
            $this->logger->error(
                sprintf(
                    'Could not encode driver options for presentation. Offending driver: %s, exception: %s',
                    $endpoint->getDriver()?->name ?? 'Unknown',
                    $e->getMessage()
                )
            );

            $form->get('driverOptions')->setData('{}');
        }

        $form->handleRequest($request);

templates/endpoints/create.html.twig
{% extends app.request.attributes.has('isModalRequest') ? 'modal.html.twig' : 'base.html.twig' %}

{% block body %}
    <h1 class="mb-3">Create a new endpoint</h1>

    <div class="row">
        <div class="col-xl-10">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h2 class="card-title">Endpoint details</h2>
                </div>

                <div class="card-body">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}

                    {{ form_row(form.name) }}
                    {{ form_row(form.application) }}
                    {{ form_row(form.url) }}
                    {{ form_row(form.driver) }}
                    {{ form_row(form.driverOptions) }}
                    <div class="d-flex">
                        <div class="me-2">
                            <a class="btn btn-outline-danger"
                               href="{{ path('web_application_details', {'id': application.id}) }}">
                                <i class="bi-arrow-left"></i>
                                Cancel
                            </a>
                        </div>
                        {{ form_row(form.submit) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/endpoints/details.html.twig
{% extends app.request.attributes.has('isModalRequest') ? 'modal.html.twig' : 'base.html.twig' %}

{% block body %}
    <div class="d-flex justify-content-between">
        <div>
            <h1>Endpoint {{ endpoint.name }}</h1>
        </div>

        <div>
            <a class="btn btn-lg btn-primary"
               href="{{ path('web_endpoint_test', {'applicationId': application.id, 'id': endpoint.id}) }}">
                <i class="bi-arrow-repeat"></i>
                Update now
            </a>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header">
            <h2 class="card-title">Metric overview</h2>

            <p class="card-subtitle">
                These are all the metrics that have been collected using this endpoint.
            </p>
        </div>

        <div class="card-body">

            <div class="row">
                {% for product, metrics in lastMetricsPerProduct %}
                    <div class="col-lg-4 col-md-6">
                        <div class="card my-3 shadow-sm">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <h3 class="card-title">{{ product }}</h3>
                                    <div>
                                        <i class="bi-three-dots-vertical"></i>
                                    </div>
                                </div>

                                <div class="row">
                                    {% for metric in metrics %}
                                        {{ include('fragments/metric/metric-block.html.twig', { metric: metric }) }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header">
            <h2 class="card-title">Metrics</h2>
        </div>
        <div class="table-flush">
            <table class="table table-hover init-datatable">
                <thead class="table-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Type</th>
                    <th scope="col">Datapoints</th>
                    <th scope="col">Last datapoint</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for metric in endpoint.metrics %}
                    <tr>
                        <th scope="row" class="align-middle">{{ metric.id }}</th>
                        <td class="align-middle">{{ metric.product }}</td>
                        <td class="align-middle">{{ metric.discriminator.name }}</td>
                        <td class="align-middle">{{ metric.datapoints.count }}</td>
                        <td class="align-middle">
                            {% if metric.lastDatapoint %}
                                {{ metric.lastDatapoint.updatedAt }}
                            {% else %}
                                N/A
                            {% endif %}
                        </td>
                        <td class="align-middle wrap-content">

                            <a class="btn btn-sm btn-primary"
                               href="{{ path('web_metric_details', {'applicationId': application.id, 'endpointId': endpoint.id, 'id': metric.id}) }}">
                                <i class="bi-eye"></i>
                                View
                            </a>

                            <a class="btn btn-sm btn-secondary"
                               href="{{ path('web_application_update', {'id': metric.id}) }}">
                                <i class="bi-pencil"></i>
                                Edit
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header">
            <h2 class="card-title">Collection logs</h2>
            <p class="card-subtitle">
                If data collection is not working as expected, these logs may help.
                You can set the retention period in the endpoint settings.
            </p>
        </div>
        <div class="table-flush">
            <table class="table table-hover init-datatable">
                <thead class="table-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Successful</th>
                    <th scope="col">Metrics created / updated</th>
                    <th scope="col">Metrics missing in response</th>
                    <th scope="col">Datapoints created / updated</th>
                    <th scope="col">Executed at</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for log in endpoint.collectionLogs %}
                    <tr>
                        <th scope="row" class="align-middle">{{ log.id }}</th>
                        <td class="align-middle">
                            {% if not log.successful %}
                                <span class="text-danger">No</span>
                            {% else %}
                                Yes
                            {% endif %}</td>
                        <td class="align-middle">
                            {{ log.createdMetricCount }} / {{ log.updatedMetricCount }}
                        </td>
                        <td class="align-middle">
                            {{ log.metricsMissingInResponseCount }}
                        </td>
                        <td class="align-middle">
                            {{ log.createdDatapointCount }} / {{ log.updatedDatapointCount }}
                        </td>
                        <td class="align-middle">
                            {{ log.createdAt }}
                        </td>
                        <td class="align-middle wrap-content">
                            <a class="btn btn-sm btn-primary"
                               href="{{ path('web_endpoint_collection_log_details', {'applicationId': application.id, 'endpointId': endpoint.id, 'id': log.id}) }}">
                                <i class="bi-eye"></i>
                                View
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/endpoints/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div>
        <div class="d-flex justify-content-between">
            <div>
                <h1>Applications</h1>
            </div>

            <div>
                <a class="btn btn-primary" href="{{ path('web_application_create') }}" role="button">
                    <i class="bi-plus-circle-fill"></i>
                    Create new application
                </a>
            </div>
        </div>
        <table class="table table-hover init-datatable">
            <thead class="table-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Groups</th>
                <th scope="col">Created</th>
                <th scope="col">Last updated</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for application in applications %}
                <tr {{ stimulus_controller('groups/actions', {
                    'deleteUrl': path('web_application_delete', {'id': application.id})
                }) }}>
                    <th scope="row" class="align-middle">{{ application.id }}</th>
                    <td class="align-middle">{{ application.name }}</td>
                    <td class="align-middle">{{ application.name }}</td>
{#                    <td class="align-middle">{{ application.groups | reduce(g => g.name) | join(', ') }}</td>#}
                    <td class="align-middle">{{ application.createdAt }}</td>
                    <td class="align-middle">{{ application.updatedAt }}</td>
                    <td class="align-middle wrap-content">

                        <a class="btn btn-sm btn-primary" href="{{ path('web_application_details', {'id': application.id}) }}">
                            <i class="bi-eye"></i>
                            View
                        </a>

                        <a class="btn btn-sm btn-secondary" href="{{ path('web_application_update', {'id': application.id}) }}">
                            <i class="bi-pencil"></i>
                            Edit
                        </a>

                        <a {{ stimulus_target('groups/actions', 'deleteButton')}} class="btn btn-sm btn-outline-danger" {{ stimulus_action('groups/actions', 'confirmDelete') }}>
                            <i class="bi-trash"></i>
                            Delete
                        </a>

                        <form {{ stimulus_target('groups/actions', 'deleteForm')}} action="{{ path('web_application_delete', {'id': application.id} ) }}" method="POST" class="d-none">
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="bi-trash-fill"></i>
                                Confirm delete
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/endpoints/update.html.twig
{% extends app.request.attributes.has('isModalRequest') ? 'modal.html.twig' : 'base.html.twig' %}

{% block body %}
    <h1>Update endpoint {{ endpoint.name }}</h1>

    <div class="row">
        <div class="col-xl-10">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h2 class="card-title">Endpoint details</h2>
                </div>

                <div class="card-body">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}

                    {{ form_row(form.name) }}
                    {{ form_row(form.application) }}
                    {{ form_row(form.url) }}
                    {{ form_row(form.driver) }}
                    {{ form_row(form.driverOptions) }}
                    <div class="d-flex">
                        <div class="me-2">
                            <a class="btn btn-outline-danger"
                               href="{{ path('web_application_details', {'id': application.id}) }}">
                                <i class="bi-arrow-left"></i>
                                Cancel
                            </a>
                        </div>
                        {{ form_row(form.submit) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}