src/Domain/Entity/Application.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Domain\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Orchestra\Domain\Repository\ApplicationDoctrineRepository;
use Orchestra\Infrastructure\Doctrine\Traits\TimestampedEntityTrait;

#[ORM\Entity(repositoryClass: ApplicationDoctrineRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Application
{
    use TimestampedEntityTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: Group::class, inversedBy: 'applications')]
    private Collection $groups;

    #[ORM\OneToMany(mappedBy: 'application', targetEntity: Endpoint::class, orphanRemoval: true)]
    private Collection $endpoints;

    public function __construct()
    {
        $this->groups = new ArrayCollection();
        $this->endpoints = new ArrayCollection();
    }

    public function addEndpoint(Endpoint $endpoint): self
    {
        if (!$this->endpoints->contains($endpoint)) {
            $this->endpoints->add($endpoint);
            $endpoint->setApplication($this);
        }

        return $this;
    }

    public function addGroup(Group $group): self
    {
        if (!$this->groups->contains($group)) {
            $this->groups->add($group);
        }

        return $this;
    }

    /**
     * @return Collection<int, Endpoint>
     */
    public function getEndpoints(): Collection
    {
        return $this->endpoints;
    }

    /**
     * @return Collection<int, Group>
     */
    public function getGroups(): Collection
    {
        return $this->groups;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @internal for test use only
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return ArrayCollection<Metric>
     */
    public function getMetrics(): ArrayCollection
    {
        return new ArrayCollection(...$this->endpoints->map(fn(Endpoint $e) => $e->getMetrics()->toArray())->toArray());
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function removeEndpoint(Endpoint $endpoint): self
    {
        if ($this->endpoints->removeElement($endpoint)) {
            // set the owning side to null (unless already changed)
            if ($endpoint->getApplication() === $this) {
                $endpoint->setApplication(null);
            }
        }

        return $this;
    }

    public function removeGroup(Group $group): self
    {
        $this->groups->removeElement($group);

        return $this;
    }
}

src/Domain/Entity/Endpoint.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Domain\Entity;

use Carbon\Carbon;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Orchestra\Domain\Endpoint\Driver\DriverEndpointInterface;
use Orchestra\Domain\Endpoint\Driver\DriverEnum;
use Orchestra\Domain\Repository\EndpointDoctrineRepository;
use Orchestra\Infrastructure\Doctrine\Traits\TimestampedEntityTrait;
use Symfony\Component\Validator\Constraints;

#[ORM\Entity(repositoryClass: EndpointDoctrineRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Endpoint implements DriverEndpointInterface
{
    use TimestampedEntityTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'endpoints')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Application $application = null;

    #[ORM\Column(length: 255)]
    private string $url = '';

    #[ORM\Column(type: 'EndpointDriverType', length: 255)]
    private ?DriverEnum $driver = null;

    #[ORM\Column]
    private array $driverOptions = [];

    #[ORM\Column]
    private ?int $interval = null;

    #[ORM\Column]
    #[Constraints\PositiveOrZero]
    private int $collectionLogRetention = 604800; // in seconds; default is a week

    #[ORM\Column(type: 'CarbonDateTimeType', nullable: true)]
    private ?Carbon $lastSuccessfulResponse = null;

    #[ORM\OneToMany(mappedBy: 'endpoint', targetEntity: Metric::class, cascade: ['persist'], fetch: 'EAGER', orphanRemoval: true)]
    private Collection $metrics;

    #[ORM\OneToMany(mappedBy: 'endpoint', targetEntity: EndpointCollectionLog::class, cascade: ['persist'], orphanRemoval: true)]
    #[ORM\OrderBy(['id' => 'DESC'])]
    private Collection $collectionLogs;

    public function __construct()
    {
        $this->metrics = new ArrayCollection();
        $this->collectionLogs = new ArrayCollection();
    }

    public function addCollectionLog(EndpointCollectionLog $collectionLog): self
    {
        if (!$this->collectionLogs->contains($collectionLog)) {
            $this->collectionLogs->add($collectionLog);
            $collectionLog->setEndpoint($this);
        }

        return $this;
    }

    public function addMetric(Metric $metric): self
    {
        if (!$this->metrics->contains($metric)) {
            $this->metrics->add($metric);
            $metric->setEndpoint($this);
        }

        return $this;
    }

    public function belongsToApplication(Application $application): bool
    {
        if (!$this->application instanceof Application) {
            return false;
        }

        return $application->getId() === $this->application->getId();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @internal for test use only
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    public function getApplication(): ?Application
    {
        return $this->application;
    }

    public function setApplication(?Application $application): self
    {
        $this->application = $application;

        return $this;
    }

    public function getDriver(): ?DriverEnum
    {
        return $this->driver;
    }

    public function setDriver(DriverEnum $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    public function getDriverOptions(): array
    {
        return $this->driverOptions;
    }

    public function setDriverOptions(array $driverOptions): self
    {
        $this->driverOptions = $driverOptions;

        return $this;
    }

    public function getInterval(): ?int
    {
        return $this->interval;
    }

    public function setInterval(int $interval): self
    {
        $this->interval = $interval;

        return $this;
    }

    public function getLastSuccessfulResponse(): ?Carbon
    {
        return $this->lastSuccessfulResponse;
    }

    public function setLastSuccessfulResponse(?Carbon $lastSuccessfulResponse): self
    {
        $this->lastSuccessfulResponse = $lastSuccessfulResponse;

        return $this;
    }

    /**
     * @return ArrayCollection<string, ArrayCollection<Metric>>
     */
    public function getMetricsPerProduct(): ArrayCollection
    {
        $collection = new ArrayCollection();

        foreach ($this->getMetrics() as $metric) {
            if (!$collection->containsKey($metric->getProduct())) {
                $collection->set($metric->getProduct(), new ArrayCollection());
            }

            $collection->get($metric->getProduct())->add($metric);
        }

        return $collection;
    }

    /**
     * @return Collection<int, Metric>
     */
    public function getMetrics(): Collection
    {
        return $this->metrics;
    }

    public function getMostRecentCollectionLog(): ?EndpointCollectionLog
    {
        // Because we sort by id, DESC
        $log = $this->getCollectionLogs()->first();

        return !$log ? null : $log;
    }

    /**
     * @return Collection<int, EndpointCollectionLog>
     */
    public function getCollectionLogs(): Collection
    {
        return $this->collectionLogs;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function removeCollectionLog(EndpointCollectionLog $collectionLog): self
    {
        if ($this->collectionLogs->removeElement($collectionLog)) {
            // set the owning side to null (unless already changed)
            if ($collectionLog->getEndpoint() === $this) {
                $collectionLog->setEndpoint(null);
            }
        }

        return $this;
    }

    public function removeMetric(Metric $metric): self
    {
        if ($this->metrics->removeElement($metric)) {
            // set the owning side to null (unless already changed)
            if ($metric->getEndpoint() === $this) {
                $metric->setEndpoint(null);
            }
        }

        return $this;
    }

    public function touchLastSuccessfulResponse(): self
    {
        $this->lastSuccessfulResponse = Carbon::now();

        return $this;
    }
}

src/Web/Form/ApplicationForm.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Web\Form;

use Orchestra\Domain\Entity\Application;
use Orchestra\Domain\Entity\Group;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApplicationForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('groups', EntityType::class, [
                'class'        => Group::class,
                'multiple'     => true,
                'expanded'     => true,
                'choice_label' => static fn(Group $u) => $u->getName(),
            ])
            ->add('submit', SubmitType::class, [
                'row_attr' => [
                    'class' => 'mb-0', // remove the mb-3 class
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Application::class,
        ]);
    }
}

src/Web/Controller/ApplicationController.php
<?php

/**
 * Copyright (c) 2023 NanoSector & Orchestra contributors
 *
 * This source code is licensed under the MIT license. See LICENSE for details.
 */

declare(strict_types=1);

namespace Orchestra\Web\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use Orchestra\Domain\Collection\MetricsPerProductCollection;
use Orchestra\Domain\Entity\Application;
use Orchestra\Domain\Entity\Metric;
use Orchestra\Domain\Entity\MetricPin;
use Orchestra\Domain\Entity\User;
use Orchestra\Domain\Repository\ApplicationRepositoryInterface;
use Orchestra\Infrastructure\Controller\AppContext;
use Orchestra\Web\Breadcrumb\Breadcrumb;
use Orchestra\Web\Breadcrumb\BreadcrumbBuilder;
use Orchestra\Web\Exception\BreadcrumbBuilderException;
use Orchestra\Web\Exception\BreadcrumbException;
use Orchestra\Web\Form\ApplicationForm;
use Orchestra\Web\Helper\BreadcrumbHelper;
use Orchestra\Web\Helper\Flash;
use Orchestra\Web\ViewModel\MetricViewModel;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[AppContext('app_management')]
#[Breadcrumb('Applications', 'web_application_index')]
class ApplicationController extends AbstractController
{
    public function __construct(
        private readonly ApplicationRepositoryInterface $applicationRepository,
        private readonly BreadcrumbBuilder $breadcrumbBuilder
    ) {
    }

    #[Route('/applications/create', name: 'web_application_create', methods: ["GET", "POST"])]
    #[Breadcrumb('Create application')]
    public function createAction(Request $request): Response
    {
        $application = new Application();

        $form = $this->createForm(ApplicationForm::class, $application);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->applicationRepository->save($application);

            $this->addFlash(Flash::OK, 'The application has been created.');

            return $this->redirectToRoute('web_application_update', ['id' => $application->getId()]);
        }

        return $this->render('applications/create.html.twig', [
            'application' => $application,
            'form'        => $form,
        ]);
    }

    #[Route('/applications/{id}/delete', name: 'web_application_delete', methods: ["POST"])]
    public function deleteAction(Application $application): Response
    {
        $this->applicationRepository->delete($application);

        $this->addFlash(Flash::OK, 'The application has been deleted.');

        return $this->redirectToRoute('web_application_index');
    }

    /**
     * @throws BreadcrumbException
     * @throws BreadcrumbBuilderException
     */
    #[Route('/applications/{id}', name: 'web_application_details', methods: ["GET"])]
    public function detailsAction(Request $request, Application $application): Response
    {
        BreadcrumbHelper::request($request)->add([
            'application' => $this->breadcrumbBuilder->application($application)
        ]);

        $pinnedMetricsPerProduct = new ArrayCollection();

        $user = $this->getUser();

        if ($user instanceof User) {
            $userPinnedMetrics = $user->decoratePinnedMetrics();
            $pinnedMetrics = $userPinnedMetrics->findPinsByApplication($application);

            $metrics = $pinnedMetrics->map(fn(MetricPin $p) => $p->getMetric());
            $perProductCollection = MetricsPerProductCollection::fromMetricCollection($metrics);

            $pinnedMetricsPerProduct = $perProductCollection->map(
                static fn(ArrayCollection $metrics) => $metrics->map(
                    fn(Metric $m) => MetricViewModel::fromLastDatapointInMetric($m)
                                                    ->setPinned($userPinnedMetrics->hasPinnedMetric($m))
                )
            );
        }

        return $this->render('applications/details.html.twig', [
            'application'             => $application,
            'pinnedMetricsPerProduct' => $pinnedMetricsPerProduct,
        ]);
    }

    #[Route('/applications', name: 'web_application_index')]
    public function indexAction(): Response
    {
        return $this->render('applications/index.html.twig', [
            'applications' => $this->applicationRepository->findAll(),
        ]);
    }

    /**
     * @throws BreadcrumbException
     * @throws BreadcrumbBuilderException
     */
    #[Route('/applications/{id}/update', name: 'web_application_update', methods: ["GET", "POST"])]
    public function updateAction(Application $application, Request $request): Response
    {
        BreadcrumbHelper::request($request)->add([
            'application' => $this->breadcrumbBuilder->application($application),
            'current'     => $this->breadcrumbBuilder->text('Update application', true),
        ]);

        $form = $this->createForm(ApplicationForm::class, $application);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->applicationRepository->save($application);

            $this->addFlash(Flash::OK, 'The application has been updated.');

            return $this->redirectToRoute('web_application_update', ['id' => $application->getId()]);
        }

        return $this->render('applications/update.html.twig', [
            'application' => $application,
            'form'        => $form,
        ]);
    }
}

templates/applications/create.html.twig
{% extends app.request.attributes.has('isModalRequest') ? 'modal.html.twig' : 'base.html.twig' %}

{% block body %}
    <h1 class="mb-3">Create a new application</h1>

    <div class="row">
        <div class="col-xl-10">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h2 class="card-title">Application details</h2>
                </div>

                <div class="card-body">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}

                    {{ form_row(form.name) }}
                    {{ form_row(form.groups) }}
                    <div class="d-flex justify-content-end">
                        <div class="me-2">
                            <a class="btn btn-outline-danger" href="{{ path('web_application_index') }}">
                                <i class="bi-arrow-left"></i>
                                Cancel
                            </a>
                        </div>
                        {{ form_row(form.submit) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/applications/details.html.twig
{% extends app.request.attributes.has('isModalRequest') ? 'modal.html.twig' : 'base.html.twig' %}

{% block body %}
    <h1>Application {{ application.name }}</h1>

    {% if pinnedMetricsPerProduct.count > 0 %}
        <div class="card shadow-sm">
            <div class="card-header">
                <h2 class="card-title">Pinned metrics</h2>
            </div>

            <div class="card-body">

                <div class="row">
                    {% for product, metrics in pinnedMetricsPerProduct %}
                        <div class="col-lg-4 col-md-6">
                            <div class="card my-3 shadow-sm">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <h3 class="card-title">{{ product }}</h3>
                                        <div>
                                            <i class="bi-three-dots-vertical"></i>
                                        </div>
                                    </div>

                                    <div class="row">
                                        {% for metric in metrics %}
                                            {{ include('fragments/metric/metric-block.html.twig', { metric: metric }) }}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}

    <div class="card shadow-sm">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <div>
                    <h2 class="card-title">Endpoints</h2>
                    <p class="card-subtitle">
                        An application can have one or more endpoints.
                        Endpoints will generate metrics which are aggregated in Orchestra.
                    </p>
                </div>

                <div>
                    <a class="btn btn-primary"
                       href="{{ path('web_endpoint_create', {'applicationId': application.id}) }}" role="button">
                        <i class="bi-plus-circle-fill"></i>
                        Create new endpoint
                    </a>
                </div>
            </div>
        </div>

        <div class="table-flush">
            <table class="table table-hover init-datatable">
                <thead class="table-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Driver</th>
                    <th scope="col">State</th>
                    <th scope="col">Last successful response</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for endpoint in application.endpoints %}
                    <tr>
                        <th scope="row" class="align-middle">{{ endpoint.id }}</th>
                        <td class="align-middle">{{ endpoint.name }}</td>
                        <td class="align-middle">{{ endpoint.driver.friendlyName }}</td>
                        <td class="align-middle">
                            {% set mostRecentLog = endpoint.mostRecentCollectionLog %}
                            {% if mostRecentLog %}
                                {% if mostRecentLog.successful %}
                                    <a href="{{ url('web_endpoint_collection_log_details', {'applicationId': application.id, 'endpointId': endpoint.id, 'id': mostRecentLog.id}) }}"
                                       class="text-success"
                                       title="ID: {{ mostRecentLog.id }}, metrics created: {{ mostRecentLog.createdMetricCount }}, metrics updated: {{ mostRecentLog.updatedMetricCount }}, datapoints updated: {{ mostRecentLog.updatedDatapointCount }}">
                                        OK
                                    </a>
                                {% else %}
                                    <a href="{{ url('web_endpoint_collection_log_details', {'applicationId': application.id, 'endpointId': endpoint.id, 'id': mostRecentLog.id}) }}"
                                       class="text-danger">
                                        Failed
                                    </a>
                                {% endif %}
                            {% else %}
                                <span class="text-muted">N/A</span>
                            {% endif %}
                        </td>
                        <td class="align-middle">{{ endpoint.lastSuccessfulResponse }}</td>
                        <td class="align-middle wrap-content">

                            <a class="btn btn-sm btn-primary"
                               href="{{ path('web_endpoint_details', {'applicationId': application.id, 'id': endpoint.id}) }}">
                                <i class="bi-eye"></i>
                                View
                            </a>

                            <a class="btn btn-sm btn-outline-primary"
                               href="{{ path('web_endpoint_test', {'applicationId': application.id, 'id': endpoint.id}) }}">
                                <i class="bi-arrow-repeat"></i>
                                Force update
                            </a>

                            <a class="btn btn-sm btn-outline-secondary"
                               href="{{ path('web_endpoint_update', {'applicationId': application.id, 'id': endpoint.id}) }}">
                                <i class="bi-pencil"></i>
                                Edit
                            </a>

                            <a {{ stimulus_target('groups/actions', 'deleteButton') }}
                                    class="btn btn-sm btn-outline-danger" {{ stimulus_action('groups/actions', 'confirmDelete') }}>
                                <i class="bi-trash"></i>
                                Delete
                            </a>

                            <form {{ stimulus_target('groups/actions', 'deleteForm') }}
                                    action="{{ path('web_endpoint_delete', {'applicationId': application.id, 'id': endpoint.id} ) }}"
                                    method="POST" class="d-none">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="bi-trash-fill"></i>
                                    Confirm delete
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/applications/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Application management</h1>

    <div class="card shadow-sm">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <div>
                    <h2 class="card-title">Applications</h2>
                    <p class="card-subtitle">
                        All registered applications are shown below.
                        If the application you want to see is not listed, you might not have access to it.
                    </p>
                </div>

                <div>
                    <a class="btn btn-primary" href="{{ path('web_application_create') }}" role="button">
                        <i class="bi-plus-circle-fill"></i>
                        Create new application
                    </a>
                </div>
            </div>
        </div>
        <div class="table-flush">
            <table class="table table-hover init-datatable">
                <thead class="table-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for application in applications %}
                    <tr {{ stimulus_controller('groups/actions', {
                        'deleteUrl': path('web_application_delete', {'id': application.id})
                    }) }}>
                        <th scope="row" class="align-middle">{{ application.id }}</th>
                        <td class="align-middle">{{ application.name }}</td>
                        <td class="align-middle wrap-content">

                            <a class="btn btn-sm btn-primary"
                               href="{{ path('web_application_details', {'id': application.id}) }}">
                                <i class="bi-eye"></i>
                                View
                            </a>

                            <a class="btn btn-sm btn-outline-secondary"
                               href="{{ path('web_application_update', {'id': application.id}) }}">
                                <i class="bi-pencil"></i>
                                Edit
                            </a>

                            <a {{ stimulus_target('groups/actions', 'deleteButton') }}
                                    class="btn btn-sm btn-outline-danger" {{ stimulus_action('groups/actions', 'confirmDelete') }}>
                                <i class="bi-trash"></i>
                                Delete
                            </a>

                            <form {{ stimulus_target('groups/actions', 'deleteForm') }}
                                    action="{{ path('web_application_delete', {'id': application.id} ) }}" method="POST"
                                    class="d-none">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="bi-trash-fill"></i>
                                    Confirm delete
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/applications/update.html.twig
{% extends app.request.attributes.has('isModalRequest') ? 'modal.html.twig' : 'base.html.twig' %}

{% block body %}
    <h1>Update application {{ application.name }}</h1>

    <div class="row">
        <div class="col-xl-10">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h2 class="card-title">Application details</h2>
                </div>

                <div class="card-body">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}

                    {{ form_row(form.name) }}
                    {{ form_row(form.groups) }}
                    <div class="d-flex justify-content-end">
                        <div class="me-2">
                            <a class="btn btn-outline-danger" href="{{ path('web_application_index') }}">
                                <i class="bi-arrow-left"></i>
                                Cancel
                            </a>
                        </div>
                        {{ form_row(form.submit) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}